### ISSUE TITLE
MemoryModule 项目能否略微改一改，让它在net8下，设置AOT之后，不要那么多的警告

### ISSUE THREAD

**Issue by Charltsing** [wwh1004/MemoryModule#1]
我很敬仰您的工作，MemoryModule 项目解决了net开发的一个重要痛点。现在net发布半年多了，AOT也逐渐成为主流，可否维护一下这个项目，让他在AOT编译时不要那么多警告。

虽然，目前没发现对程序运行有什么影响。

![捕获](https://github.com/user-attachments/assets/36c01705-3651-4a8c-9649-709a639792ac)

顺便说一下，我仅使用MemoryModuleLite中的三个cs文件
![1](https://github.com/user-attachments/assets/a43f71c0-d373-4463-9897-39f794a0f4f3)

严重性	代码	说明	项目	文件	行	禁止显示状态	详细信息
警告(活动)	IL3050	Using member 'System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(nint, Type)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. Marshalling code for the delegate might not be available. Use the GetDelegateForFunctionPointer<TDelegate> overload instead.	imageinfo-sharp	\MemoryModuleLite\MemoryModule.cs	117		
警告(活动)	IL3050	Using member 'System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(nint, Type)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. Marshalling code for the delegate might not be available. Use the GetDelegateForFunctionPointer<TDelegate> overload instead.	imageinfo-sharp	\MemoryModuleLite\MemoryModuleC.cs	341		
警告(活动)	IL3050	Using member 'System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(nint, Type)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. Marshalling code for the delegate might not be available. Use the GetDelegateForFunctionPointer<TDelegate> overload instead.	imageinfo-sharp	\MemoryModuleLite\MemoryModuleC.cs	627		
警告(活动)	IL3050	Using member 'System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(nint, Type)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. Marshalling code for the delegate might not be available. Use the GetDelegateForFunctionPointer<TDelegate> overload instead.	imageinfo-sharp	\MemoryModuleLite\MemoryModuleC.cs	635		
警告(活动)	IL3050	Using member 'System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(nint, Type)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. Marshalling code for the delegate might not be available. Use the GetDelegateForFunctionPointer<TDelegate> overload instead.	imageinfo-sharp	\MemoryModuleLite\MemoryModuleC.cs	725		
警告(活动)	IL3050	Using member 'System.Runtime.InteropServices.Marshal.SizeOf(Type)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. Marshalling code for the object might not be available. Use the SizeOf<T> overload instead.	imageinfo-sharp	\MemoryModuleLite\NativeMethods.cs	67		
警告(活动)	IL3050	Using member 'System.Runtime.InteropServices.Marshal.SizeOf(Type)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. Marshalling code for the object might not be available. Use the SizeOf<T> overload instead.	imageinfo-sharp	\MemoryModuleLite\NativeMethods.cs	75		
警告(活动)	IL3050	Using member 'System.Runtime.InteropServices.Marshal.SizeOf(Type)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. Marshalling code for the object might not be available. Use the SizeOf<T> overload instead.	imageinfo-sharp	\MemoryModuleLite\NativeMethods.cs	83		
警告(活动)	IL3050	Using member 'System.Runtime.InteropServices.Marshal.SizeOf(Type)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. Marshalling code for the object might not be available. Use the SizeOf<T> overload instead.	imageinfo-sharp	\MemoryModuleLite\NativeMethods.cs	190		
警告(活动)	IL3050	Using member 'System.Runtime.InteropServices.Marshal.SizeOf(Type)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. Marshalling code for the object might not be available. Use the SizeOf<T> overload instead.	imageinfo-sharp	\MemoryModuleLite\NativeMethods.cs	200

**Comment by wwh1004** [comment]
改完了。

**Comment by wwh1004** [comment]
MemoryModule和MemoryModuleLite一样的，就是MemoryModuleLite删了资源获取，只小了4kb，没什么区别。
